// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyQ0fELcFfPUoNj9eehtrEKKW3iu-JLo',
    appId: '1:832805495227:web:35cd9ee3cda9b32ca3a49e',
    messagingSenderId: '832805495227',
    projectId: 'hjamty',
    authDomain: 'hjamty.firebaseapp.com',
    storageBucket: 'hjamty.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmJv0qKrf-AQCGd6xY0Badttwi745tg3Q',
    appId: '1:832805495227:android:09469a635e89fb25a3a49e',
    messagingSenderId: '832805495227',
    projectId: 'hjamty',
    storageBucket: 'hjamty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSKRfrs8GQpgMjax3J5a3fK_N8QDWb638',
    appId: '1:832805495227:ios:f1ea10362905e487a3a49e',
    messagingSenderId: '832805495227',
    projectId: 'hjamty',
    storageBucket: 'hjamty.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSKRfrs8GQpgMjax3J5a3fK_N8QDWb638',
    appId: '1:832805495227:ios:f1ea10362905e487a3a49e',
    messagingSenderId: '832805495227',
    projectId: 'hjamty',
    storageBucket: 'hjamty.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFyQ0fELcFfPUoNj9eehtrEKKW3iu-JLo',
    appId: '1:832805495227:web:b8aa7d4ce19603cba3a49e',
    messagingSenderId: '832805495227',
    projectId: 'hjamty',
    authDomain: 'hjamty.firebaseapp.com',
    storageBucket: 'hjamty.firebasestorage.app',
  );
}
