import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { PrismaClient, ApprovalStatus, Role } from '../generated/prisma/index.js';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';

const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL! });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const CLIENT_COUNT = 10;
const PATRON_COUNT = 10;
const EMPLOYEES_PER_SALON = 10;
const SERVICES_PER_SALON = 10;
const DEFAULT_PASSWORD = '123456';

function pad2(value: number): string {
  return value.toString().padStart(2, '0');
}

function makeRunToken(): string {
  return Date.now().toString().slice(-6);
}

function makePhone(prefix: string, runToken: string, ...parts: number[]): string {
  return `${prefix}${runToken}${parts.map((p) => pad2(p)).join('')}`;
}

function createWorkingHours() {
  return Array.from({ length: 7 }, (_, idx) => ({
    dayOfWeek: idx + 1,
    openTime: '09:00',
    closeTime: '19:00',
    isDayOff: false,
  }));
}

async function createClients(runToken: string, passwordHash: string) {
  let created = 0;

  for (let i = 1; i <= CLIENT_COUNT; i += 1) {
    const phoneNumber = makePhone('31', runToken, i);

    await prisma.user.create({
      data: {
        fullName: `Seed Client ${i}`,
        phoneNumber,
        passwordHash,
        role: Role.CLIENT,
        isVerified: true,
        profile: {
          create: {
            email: `seed.client.${runToken}.${i}@7jemty.local`,
            address: `Client Address ${i}`,
          },
        },
      },
    });

    created += 1;
  }

  return created;
}

async function createPatronsWithSalons(runToken: string, passwordHash: string) {
  let patronsCreated = 0;
  let salonsCreated = 0;
  let employeesCreated = 0;
  let servicesCreated = 0;

  for (let p = 1; p <= PATRON_COUNT; p += 1) {
    const patronPhone = makePhone('41', runToken, p);

    const patron = await prisma.user.create({
      data: {
        fullName: `Seed Patron ${p}`,
        phoneNumber: patronPhone,
        passwordHash,
        role: Role.PATRON,
        isVerified: true,
        profile: {
          create: {
            email: `seed.patron.${runToken}.${p}@7jemty.local`,
            address: `Patron Address ${p}`,
          },
        },
      },
    });
    patronsCreated += 1;

    const salon = await prisma.salon.create({
      data: {
        patronId: patron.id,
        name: `Seed Salon ${p}`,
        description: `Demo salon ${p} generated by script`,
        contactPhone: patronPhone,
        address: `Salon Address ${p}`,
        speciality: 'Hair',
        approvalStatus: ApprovalStatus.APPROVED,
        workingHours: {
          create: createWorkingHours(),
        },
      },
    });
    salonsCreated += 1;

    for (let e = 1; e <= EMPLOYEES_PER_SALON; e += 1) {
      const employeePhone = makePhone('51', runToken, p, e);

      await prisma.user.create({
        data: {
          fullName: `Seed Employee ${p}-${e}`,
          phoneNumber: employeePhone,
          passwordHash,
          role: Role.EMPLOYEE,
          isVerified: true,
          workplaceSalonId: salon.id,
          profile: {
            create: {
              email: `seed.employee.${runToken}.${p}.${e}@7jemty.local`,
              bio: `Employee ${e} at salon ${p}`,
            },
          },
        },
      });

      employeesCreated += 1;
    }

    const servicesPayload = Array.from({ length: SERVICES_PER_SALON }, (_, idx) => {
      const serviceNumber = idx + 1;
      return {
        salonId: salon.id,
        name: `Service ${p}-${serviceNumber}`,
        description: `Seed service ${serviceNumber} for salon ${p}`,
        price: 15 + serviceNumber * 5,
        durationMinutes: 20 + serviceNumber * 5,
      };
    });

    await prisma.service.createMany({
      data: servicesPayload,
    });

    servicesCreated += servicesPayload.length;

    console.log(`Salon ${p}/${PATRON_COUNT} ready -> employees: ${EMPLOYEES_PER_SALON}, services: ${SERVICES_PER_SALON}`);
  }

  return {
    patronsCreated,
    salonsCreated,
    employeesCreated,
    servicesCreated,
  };
}

async function main() {
  const runToken = makeRunToken();

  console.log('Seeding demo data...');
  console.log(`Run token: ${runToken}`);
  console.log(`Default password for all users: ${DEFAULT_PASSWORD}`);

  const passwordHash = await bcrypt.hash(DEFAULT_PASSWORD, 10);

  const clientsCreated = await createClients(runToken, passwordHash);
  const {
    patronsCreated,
    salonsCreated,
    employeesCreated,
    servicesCreated,
  } = await createPatronsWithSalons(runToken, passwordHash);

  console.log('');
  console.log('Done. Summary:');
  console.log(`- Clients created: ${clientsCreated}`);
  console.log(`- Patrons created: ${patronsCreated}`);
  console.log(`- Salons created: ${salonsCreated}`);
  console.log(`- Employees created: ${employeesCreated}`);
  console.log(`- Services created: ${servicesCreated}`);
}

main()
  .catch((error) => {
    console.error('Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });