export const CLIENT_CANCELLATION_LOCK_HOURS = 3;
export const CLIENT_CANCELLATION_LOCK_MINUTES = CLIENT_CANCELLATION_LOCK_HOURS * 60;
export const CLIENT_CANCELLATION_PRELOCK_REMINDER_MINUTES = CLIENT_CANCELLATION_LOCK_MINUTES + 10;
