const Map<String, String> tn = {
  // General
  'home': 'Accueil',
  'language': 'Lougha',
  'notifications': 'Notificatiounet',
  'help_support': 'Mo3awna',
  'terms': 'A7kem amma',
  'logout': 'Okhrej',
  'cancel': 'Batel',
  'close': 'Sakker',
  'confirm': 'Aked',
  'edit': 'Badel',
  'delete': 'Faskh',

  // Client Home Page
  'search_placeholder': 'Lawej aala salon, service...',
  'greeting': 'Ahla 👋',
  'top_categories': 'Chnowa tawa?',
  'near_you': '9rab lik',
  'top_rated': 'A7sen les Salons 👑',
  'all_salons': 'Kol Salounet',
  'explore': 'Iktachef',

  // Appointments
  'my_appointments': 'Rendez-vous Mte3i',
  'upcoming': 'Jeyin',
  'history': 'Lqdom',
  'next_appointment': 'Rendez-vous jey',
  'see_on_map': 'Chouf fil map 🗺️',
  'in_time': 'Mazel',
  'status_confirmed': 'M\'akd',
  'status_completed': 'Kmal',
  'status_cancelled': 'Tbatel',
  'status_in_progress': 'Fi wosst',
  'status_pending': 'Mazel',
  'status_declined': 'Morfoudh',
  'time_passed': 'L\'wa9t r7el',
  'time_remaining_hours_min': 'Mazal {0}h {1}min',
  'time_remaining_min': 'Mazal {0}min',
  'time_remaining_sec': 'Mazal {0}s',

  // Filters
  'all': 'Lkol',
  'filter_by_date': 'Filtri b tari5',
  'clear_filters': 'Nadhaf les filtres',

  // Booking
  'book_appointment': 'A7jez RDV',
  'choose_barber': '1. Ekhtar l\'hajem mte3ek',
  'date_time': '2. Nharetha wel wa9t',
  'haircut_model': '3. Modele mtaa hjema (Optionnel)',
  'add_photo_gallery': 'Zid taswira (mel galerie)',
  'photo_added_success': 'Taswira tzadit mriguel',
  'confirm_appointment': 'Confirmer le Rendez-vous',
  'pay_on_site': 'Khalles sur place',
  'appointment_confirmed': 'Rendez-vous t\'aked ✅',
  'any_barber': 'Ay wahed',

  // Profile
  'my_profile': 'Profil Mte3i',
  'my_activities': 'Activités Mte3i',
  'product_orders': 'Comandeti mtaa Produits',
  'favorite_salons': 'Salouneti l\'Favoris',
  'settings': 'Parametres',
  'shop': 'Boutique',
  'appointments_short': 'RDV Mte3i',
  'products': 'Produits',
  'profile': 'Profil',
  'search_product': 'Lawwej 3la produit...',
  'category_all': 'Kol',
  'category_hair': 'Cha3r',
  'category_beard': 'Le7ya',
  'category_face': 'Wajh',
  'category_accessories': 'Accessoires',
  'added_to_cart': 'tzed lel panier 🛒',
  'admin_dashboard': 'Admin Dashboard',
  'welcome_admin': 'Bienvenue Admin!',
  'connect': 'Connecti',
  'welcome_back': 'Marhba bik marra okhra !',
  'forgot_password': 'Nsitt l\'mot de passe ?',
  'logged_in_successfully': 'Dkholt mriguel !',
  'no_account_yet': 'Ma aandekch compte ? ',
  'create_account': 'Aamel compte',
  'passwords_do_not_match': 'Mot de passe mouch kif kif',
  'all_set': 'Jawwek mriguel 🎉',
  'error_issue': 'Mochkla',
  'join_7jemty_enjoy_services':
      'Idkhol l 7jemty w temtaa b les services mteana.',
  'i_am_salon_owner': 'Ena moulé salon (Patron)',
  'check_this_to_add_salon': 'Cochi hethi ken theb tzid salon mte3ek',
  'already_have_account': 'Aandek compte deja ?',
  'connect_action': 'Connecter',
  'full_name': 'Esmek l\'kemel',
  'phone_number_label': 'Numrou Tlifoun',
  'password_short': 'Mot de passe',
  'confirm_password_hint': 'Aawed l\'mot de passe',
  'field_required': 'Hedha lezem taamrou',
  'sign_in_title': 'Connecti',
  'sign_up_title': 'Aamel compte',
  'leave_review': '⭐ Khali avis',
  'rebook': '↻ Aawed Ahjez',
  'date_example': '📅 24 Fév - 14:00',
  'barber_king_name': 'Barber King 👑',
  'haircut_beard_price': 'Hjema + Lihya - 25 DT',
  'barber_sami': 'Hajem: Sami',
  'directions': 'Voir en maps',
  'attention': 'Rod belek',
  'confirm_cancel_appointment':
      'Met\'aked theb tbatel e-rendez-vous?\n\n⚠️ Kan tbatel 3 marrat wra baadhom comptek yetbloka.',
  'emergency_cancel': 'Annulation en urgence',
  'emergency_cancel_title': 'Annulation en urgence',
  'confirm_emergency_cancel_appointment':
      'Met\'aked theb tbatel e-rendez-vous b urgence?\n\nHedhi exception tnajem testaamelha 3 marrat bark fi 2 mois. Tawa el confirmation hedhi UI bark.',
  'go_back': 'Rjou3',
  'appointment_cancelled': 'Rendez-vous tbatel',
  'yes_cancel': 'Ey, Batel',
  'yes_emergency_cancel': 'Ey, Batel',
  'congratulations': 'Sa77atoulek!',
  'appointment_with_ahmed_finished':
      'Rendez-vous mte3ek maa Ahmed fi salon \'Barbershop VIP\' kmal.',
  'did_you_like_haircut': '3jebtek l7jema?',
  'review_sent_thank_you': 'Avis tbaath mriguel! Aaychek 🎉',
  'send_review': 'Abaath l\'avis',
  'skip': 'Fout',
  'city_ariana_tunis': 'Ariana, Tunis',
  'dynamic_today_time': 'Lyoum, {0}',
  'opening_map': 'Kaaed yhel fel map 🗺️',
  'see_on_map_action': 'Chouf fil map 🗺️',
  'today_15_00': 'Lyoum, 15:00',
  'barber_king_haircut': 'Barber King - Coupe Cheveux + Barbe',
  'remaining_2h_30min': 'Mazel 2h 30min',
  'status_confirmed_badge': 'M\'akd',
  'reserved': 'Resservi',
  'my_cart': 'Mon Panier',
  'total_to_pay': 'Total à payer',
  'order_validated_successfully': 'Commande validée avec succès 🎉',
  'validate_order': 'Valider la commande',
  'your_cart_is_empty': 'Votre panier est vide',
  'return_to_shop': 'Retourner à la boutique',
  'quantity_2': '2',
  'professional_salon_brand': 'Marque / Salon Professionnel',
  'description_title': 'Description',
  'professional_product_desc':
      'Ce produit professionnel est spécialement conçu pour offrir une tenue parfaite tout au long de la journée. Idéal pour tous les types de cheveux, il ne laisse pas de résidus et se lave facilement.',
  'usage_tips': 'Conseils d\'utilisation',
  'apply_on_dry_hair': 'Appliquer sur cheveux secs ou légèrement humides.',
  'added_to_cart_success': 'Ajouté au panier avec succès 🛒',
  'add_to_cart_btn': 'Ajouter au panier',
  'sami_name': 'Sami',
  'sami_email': 'sami@gmail.com',
  'tunisian_lang': 'Tounsi',
  'english_lang_title': 'English',
  'redirecting_to_reservation': 'Redirection vers la réservation...',
  'reserve_this_style': 'Réserver ce style',
  'rating_4_9': '4.9',
  'based_on_120_reviews': 'Basé sur 120 avis',
  'open_status': 'Ouvert',
  'address_ariana': 'Avenue Habib Bourguiba, Ariana',
  'reviews_120': ' (120 avis)',
  'reserve_btn': 'Réserver',
  'starting_from': 'A partir de...',
  'tab_reviews': 'Avis',
  'tab_details': 'Aal salon',
  'tab_specialist': 'Specialistes',
  'services_tab_val': 'Services',
  'tab_appointments': 'Rendez-vous',
  'about_tab': 'Aal salon',
  'about_title': 'À propos',
  'location_title': 'Location',
  'open_in_maps': 'Ouvre Maps',
  'call_btn': 'APPELER',
  'social_btn': 'SOCIAL',
  'maps_btn': 'MAPS',
  'salon_description_placeholder': 'Salon jdida mar7be bikom houni.',
  'click_to_interact': 'CLICK TO INTERACT WITH MAPS',
  'open_until': 'Ouvert jusqu\'à {0}',
  'added_info_successfully': 'Zidna les infos mriguel',
  'other_details': 'Tafasil okhra',
  'do_it_later': 'Baadin',
  'few_details_left': 'Mazzal chwaya tafasil',
  'add_description_number':
      'Zid description w nemrou bech tzid tjib les clients (Optionnel).',
  'save_info': 'Sajel les infos',
  'skip_this_step': 'Fout l\'etape hethi',
  'congrats': 'Mabrouk! 🎉',
  'salon_created_successfully': 'Salon mte3ek thal mriguel',
  'my_salon': 'Salon mte3i',
  'manage_your_salon': 'Riguel Salon mte3ek',
  'give_salon_name_address': 'Aati esm w adresse l salon mte3ek.',
  'create_salon_action': 'Aamel salon',
  'updating': 'Kaad ybadal...',
  'updated_l': 'Badalna l',
  'my_agenda': 'Agenda mte3i',
  'no_appointments_today': 'Ma famma hatta rendez-vous lyoum.',
  'reject_btn': 'Orfodh',
  'accept_btn': 'Ikbel',
  'finished_haircut_q': 'Kmalt l\'hjema ?',
  'app_name_7jemty': '7jemty',
  'salon_name_label': 'Esm Salon',
  'no_salon_found': 'Ma famma hatta salon.',
  'create_your_salon': 'Aamel salon mte3ek',
  'reload_btn': 'Aawed chargi',
  'opened_status': 'Mahloul',
  'zero_reviews': '(0 avis)',
  'about_salon': 'Aal salon',
  'contact_label': 'Contact',
  'your_services_will_appear_here': 'Les services mte3ek bech yodh\'hrou houni',
  'no_client_reviews': 'Ma famma hatta avis mtaa client tawa.',
  'error_title': 'Erreur',
  'saving_status': 'Kaad ysajjel...',
  'saved_successfully': 'Tsayyev mriguel 🎉',
  'l_prefix': 'L',
  'creating_account_status': 'Kaad yasnaa fi compte...',
  'specialist_added': 'Zadna specialiste 🎉',
  'specialist_updated': 'Specialiste tbadel mriguel',
  'specialist_deleted': 'Specialiste tnaha men equipe',
  'salon_settings': 'Parametres mtaa salon',
  'save_everything': 'Sajjel kol chay',
  'info_tab': 'Info',
  'team_tab': 'Equipe',
  'schedule_tab': 'Wakt',
  'photos_tab': 'Tsawer',
  'general_info': 'Maaloumet aamma',
  'services_management': 'Gestion mtaa les services (Mazel)',
  'tab_services': 'Services',
  'add_new_service': 'Zid service',
  'save_service': 'Sajel service',
  'edit_service': 'Badel service',
  'update_service': 'Sajel ta3dil service',
  'service_added': 'Service tzad mriguel 🎉',
  'service_updated': 'Service tbadel mriguel',
  'service_deleted': 'Service tfasakh',
  'delete_service_confirm_title': 'Tfassakh service?',
  'delete_service_confirm_desc': 'Metaked theb tfassakh service {0}?',
  'service_name': 'Esm service',
  'service_name_hint': 'Ex: Fade haircut',
  'price_tnd': 'Soum (TND)',
  'price_hint': 'Ex: 20',
  'duration_hint': 'Ex: 30',
  'name_price_time_required': 'Esm, soum w duration lezm',
  'no_data_found': 'Mafamach data',
  'manage_team': 'Riguel l\'equipe',
  'new_specialist': 'SPECIALISTE JDID',
  'url_label': 'URL',
  'upload_from_gallery': 'Galerie',
  'image_optional': 'Tswira (optionnel)',
  'or_put_image_url': 'Walla hot lien mta3 tswira',
  'upload_photo': 'uploadi taswira',
  'save_btn': 'Sajjel',
  'cancel_action_2': 'Batel',
  'no_specialist_added': 'Ma zadet hatta specialiste',
  'edit_specialist': 'Badel specialiste',
  'update_specialist': 'Sajel el ta3dil',
  'name_phone_required': 'Esm w numrou tlifoun lezm',
  'delete_specialist_confirm_title': 'Tfassakh specialiste?',
  'delete_specialist_confirm_desc': 'Metaked theb tnahi {0} men l equipe?',
  'opening_time': 'Wakt lhallen',
  'time_09_00': '09:00 AM',
  'empty_text': 'à',
  'time_06_00': '06:00 PM',
  'salon_photos': 'Tsawer el salon',
  'add_salon_photos': 'ZID TSARWER LEL SALON',
  'download_photo': 'Techargi taswira',
  'new_photo': 'TASWIRA JDIDA',
  'all_appointments': 'Tous les Rendez-vous',
  'my_calendar': 'Mon Calendrier',
  'hello_test': 'hello  test monta',
  'appointments_today_fr': 'RDV Aujourd',
  'information_title': 'Information',
  'no_appointments_today_fr':
      'Vous n\'avez aucun rendez-vous pour aujourd\'hui.',
  'ok_btn': 'OK',
  'quick_access_menu': 'Quick Access',
  'upcoming_appointments_fr': 'Prochains Rendez-vous',
  'welcome_to_7ajemty': 'Mar7ba bik fi 7ajamty',
  'who_are_you_today': 'Chkoun enti lyoum?',
  'barber_space': 'Espace 7ajem',
  'barber_space_wip': 'Hetha l\'espace mta3 l\'7ajem (En cours de dev...)',
  'today_appointments_title': 'Rendez-vous d\'aujourd\'hui',
  'subscription_title': 'Abonnement',
  'status_active': 'Statut: Actif',
  'number_four': '4',
  'remaining_appointments': 'RDV restants',
  'renew_btn': 'Renouveler',
  'el_baze_barberia': 'EL BAZE BARBERIA',
  'verified_status': 'Vérifié',
  'haircut_history': 'Historique des Coupes',
  'see_all_btn': 'Voir tout',
  'settings_fr': 'Paramètres',
  'subscription_status': 'Statut Abonnement',
  'premium_tier': 'PREMIUM',
  'phone_must_be_8_digits': 'El nemrou yelzem ykoun mtaa 8 ar9am',
  'password_must_be_6_chars':
      'El mot de passe yelzem ykoun fih au moins 6 hrouf',
  'no_slots_available': 'Ma famma hatta wa9t feragh lyoum.',
  'no_professional_found_update': 'Ma famma hatta hajem. Riguel salon mte3ek.',
  'unknown': 'Inconnu',
  'total': 'Total',
  'unknown_salon': 'Salon inconnu',
  'unassigned_professional': 'Hajem mouch mawjoud',
  'professional': 'Hajem',
  'thank_you': 'Aychek!',
  'review_added_success': 'L\'avis mte3ek tzad mriguel.',
  'error': 'Ghalta',
  'please_select_rating': 'Aman ekhtar note.',
  'your_comment_optional': 'Taali9ek (Ken theb)',
  'send': 'Ab3ath',
  'setup_salon': 'Riguel Salon mte3ek',
  'salon_identity': 'Identité du salon',
  'salon_identity_desc':
      'Hatt les infos de base mtaa el salon mte3ek bech les clients yal9aweh bshoula.',
  'salon_name_req': 'Esm Salon *',
  'salon_name_hint': 'ex: Barbershop VIP',
  'salon_name_validation': 'Esem e-salon lezem',
  'address_req': 'Adresse complète *',
  'address_hint': 'ex: 12 Rue Habib Bourguiba, Tunis',
  'address_validation': 'L\'adresse lezem tkon s7i7a',
  'google_maps_optional': 'Lien Google Maps (Optionnel)',
  'google_maps_hint': 'Copie le lien mel Maps w hatou lenna',
  'speciality_optional': 'Spécialité (Optionnel)',
  'speciality_hint': 'ex: Coiffure, Esthétique...',
  'presentation_optional': 'Présentation (Optionnel)',
  'presentation_desc': 'A3ti aktar tafasil bech tjib aktar clients.',
  'description_label': 'Description',
  'description_hint': 'Chneya les services w el jaw fel salon?',
  'contact_phone': 'Numéro de contact',
  'contact_phone_hint': 'Numrou tlifoun',
  'website_label': 'Site web',
  'website_hint': 'https://www.mon-salon.com',
  'skip_step': 'Fout l\'etape',
  'cover_photo': 'Photo de couverture',
  'cover_photo_desc': 'Taswira mezyena ll salon mte3ek tzid ml iqbal.',
  'upload_photo_prompt': 'Nzel lena bech tplodi taswira',
  'or_use_link': 'Wala aamel lien',
  'use_url': 'Astaa\'mel URL',
  'finish': 'Terminer',
  'salon_created_success_title': 'Mabrouk! 🎉',
  'salon_created_success_desc': 'Salon mte3ek thal mriguel',
  'total_users': 'el users Kol ',
  'total_salons': 'e salonet Kol ',
  'pending_approvals': 'Salonet mazalou mouch approuvi',
  'system_overview': 'Chnowa fama jdid',
  'administrative_actions': 'Administrative Actions',
  'manage_users': 'Riguel el users',
  'users_management_desc': 'Chouf wala faskh el users',
  'manage_salons': 'Riguel el salonet',
  'salons_management_desc': 'Approuvi wala suspendi el salonet',
  'delete_user_q': 'Tfassakh el user?',
  'delete_user_desc': 'Met\'aked theb tfassakh hal user? Maatesh tarjaa fiha.',
  'delete_salon_confirm': 'Tfassakh el salon?',
  'delete_salon_warning':
      'Hethyya bech tfassakh kol chay mtaa el salon lel abed.',
  'peek_view': 'T\'atalla3 / Peek',
  'approve': 'Approuvi',
  'suspend': 'Suspendi',
  'reactivate': 'Raja3 khedem',
  'admin_profile_desc': 'Riguel el information personelle mte3ek',
  'orders_remaining': 'Mazzalou {0} commandes',
  'favorite_salons_count': '{0} salonet',
  'favorites_empty_title': 'Mazel ma aandek hata salon favoris',
  'favorites_empty_subtitle':
      'Ki ta3mel like l salon, taw tal9ahom l houni b sor3a.',

  // Appointment Details Bottom Sheet
  'appointment_details_title': 'Détails du Rendez-vous',
  'date_and_time': 'Date et Heure',
  'estimated_end': 'Fin estimée: {0}',
  'client_label': 'Client',
  'specialist_label': 'Spécialiste',
  'salon_label': 'Salon',
  'services_label': 'Services',
  'no_service_selected': 'Aucun service sélectionné',
  'total_label': 'Total:',

  // Search Page
  'search_hint': 'Lawej aala salon, service...',
  'no_results_found': 'Ma l9inech ntija...',
  'salon_name_default': 'Nom du salon',
  'address_unavailable': 'Adresse non disponible',
  'search_empty_state': 'Lawj 3la 7ajjem wala service...',

  // Client Home & Appointments
  'professional_label': 'Professionnel: {0}',
  'category_haircut': 'Hjema',
  'category_facial': 'Soin Visage',
  'category_kids': 'Sghar',
  'review_modal_title': 'Sa77a L\'7jema!',
  'review_modal_desc': 'Rendez-vous mte3ek maa {0} fi salon \'{1}\' kmal.',
  'review_modal_question': '3jebtek l7jema?',
  'review_comment_hint': 'Khali commentaire (optionnel)...',
  'submit_review_btn': 'Abaath l\'avis',
  'skip_btn': 'Fout',
  'close_btn': 'Fermer',
  'start_service_btn': 'jee lclient',
  'no_show_btn': 'majech lclient',
  'no_show_dialog_title': 'El client majech?',
  'no_show_dialog_desc':
      'T7eb tlaghi rendez-vous wala tzid 15mn lel client w lel specialist planning?',
  'no_show_confirm_btn': 'Mta2ked, majech',
  'postpone_15_btn': 'Nsanoh 15mn',
  'postpone_15_success': 'Rendez-vous t2ajal 15mn w planning etbadel.',

  // System & Messages
  'status_updated': 'Statut mis à jour: {0}',
  'error_updating_status': 'Erreur lors de la mise à jour',
  'product_added_to_cart': '{0} ajouté! 🛒',
  'url_hint': 'https://...',
  'review_experience_hint': 'Racontez votre expérience...',
  'error_with_message': 'Erreur: {0}',
  'sms_code_sent': 'Un code vous a été envoyé par SMS.',
  'code_must_be_6_digits': 'Le code doit contenir exactement 6 chiffres.',
  'account_verified_success': 'Votre compte a été vérifié et créé avec succès.',

  // Admin Space
  'edit_user_profile': 'Editer Utilisateur & Profil',
  'verified_label': 'Vérifié',
  'speciality_title_label': 'Titre de Spécialité',
  'bio_label': 'Bio',
  'edit_salon_info': 'Editer les infos du Salon',
  'no_data_available': 'Aucune donnée disponible.',
  'coupes_count': '{0} coupes',

  // Booking Flow
  'book_appointment_for': 'Réservation pour: {0}',
  'choose_your_services': 'Choix des services',
  'no_service_available': 'Aucun service disponible',
  'duration_min': '{0} min',
  'choose_professional_title': 'Choix du professionnel',
  'date_and_time_step': 'Date et heure',
  'select_at_least_one_service': 'Veuillez sélectionner au moins un service',
  'select_barber_validation': 'Veuillez choisir un professionnel',
  'select_time_validation': 'Veuillez choisir un horaire',
  'login_to_book': 'Connectez-vous pour réserver',
  'phone_number': 'Numéro de téléphone',
  'password': 'Mot de passe',
  'login': 'Se connecter',
  'next': 'Suivant',
  'welcome_exclamation': 'Bienvenue!',
  'booking_error_title': 'Erreur de réservation',
  'error_loading_salon_details': 'Erreur lors du chargement des détails',
  'booking_created_success': 'Votre réservation a réussi!',

  // Admin Labels
  'full_name_label': 'Nom et Prénom',
  'phone_label': 'Téléphone',
  'email_label': 'Email',
  'speciality_label': 'Spécialité',
  'contact_phone_label': 'Téléphone de Contact',
  'address_label': 'Adresse',
  'decline_btn': 'Refuser',
  'status_rebooked': 'Rebooked',
  'active': 'Active',
  'deactivated': 'Desactivé',
  'waiting_approval': 'Waiting for approval',
  'salon_not_active_popup_desc': 'Salon mte3ek mazel mouch active w mahouch bech yban fel accueil hata yetsada9 men admin.',
  'based_on_n_reviews': 'Based on {0} reviews',
  'no_reviews_yet': 'Ma famma 7atta avi ltaw',
  'rate_this_salon': '9ayyem hal saloun',
  'thank_you_for_review': 'Yaatik essa7a ala rayek! ⭐',
  'send_the_review': 'Ab3ath l\'avi',

  // Profile Edits
  'personal_info': 'Maaloumet chakhsiya',
  'first_name': 'Esm',
  'last_name': 'Laqab',
  'email_address': 'Adresse e-mail',
  'address': 'Adresse',
  'profile_photo': 'Taswiret l\'profil',
  'uploading_progress': 'Gaad ytalla3... {0}%',
  'choose_image': 'Ekhtar taswira',
  'or_paste_url': 'Wala hot l\'URL',
  'processing': 'Gaad yriguel...',
  'success': 'Temm binajeh',
  'image_uploaded_success': 'Taswira tzadit mriguel',
  'upload_error': 'Ghalta fel téléchargement',
  'feature_soon': 'Mazel ma rakebnehech',
  'profile_updated': 'Profil tbadel mriguel',
  'no_email': 'Ma famech e-mail',

  // Calendar Specialists
  'moi_patron': 'Ena (Moi)',
  'all_specialists': 'Kol el 7ajjema',
  'verify_phone': 'Vérifier le numéro',
  'otp_sent_to': 'Un code OTP a été envoyé au',
  'verify': 'Vérifier',
  'resend_code': 'Renvoyer le code',
  'wait_before_resend': 'Renvoyer dans {0}s',
  'report_btn': 'Signaler',
  'report_review_title': 'Signaler cet avis',
  'report_reason_label': 'Raison',
  'report_review_hint': 'Ekteb 3leh l\'avis hetha 5ayeb...',
  'report_review_success': 'Signalement tba3ath lel admin.',
  'manage_review_reports': 'Gestion signalements avis',
  'no_review_reports': 'Ma fama hata signalement tawa.',
  'manage_user_alerts': 'Alertes users',
  'no_user_alerts': 'Ma fama hata alerte user tawa.',
  'review_report_action_title': 'Traitement signalement',
  'review_report_admin_note': 'Note admin (optionnel)',
  'warn_user_label': 'Ba3ath tanbih lel user',
  'ban_user_label': 'Banir compte user',
  'review_report_resolved': 'Signalement tetsalla7.',
  'report_from': 'Signalé par',
  'review_owner': 'Moula l\'avis',
  'report_message': 'Message signalement',
  'reported_review': 'Avis signalé',
  'keep_review_btn': 'Khalih l\'avis',
  'delete_review_btn': 'Fas5 l\'avis',
};
