const Map<String, String> en = {
  // General
  'home': 'Home',
  'language': 'Language',
  'notifications': 'Notifications',
  'help_support': 'Help & Support',
  'terms': 'Terms & Conditions',
  'logout': 'Logout',
  'cancel': 'Cancel',
  'close': 'Close',
  'confirm': 'Confirm',
  'edit': 'Edit',
  'delete': 'Delete',
  'ok_btn': 'OK',
  'save_btn': 'Save',
  'error_title': 'Error',
  'information_title': 'Information',

  // Client Home Page
  'search_placeholder': 'Search for salon, service...',
  'greeting': 'Hello 👋',
  'top_categories': 'Quick Categories',
  'near_you': 'Near You',
  'top_rated': 'Top Rated Salons 👑',
  'all_salons': 'All Salons',
  'explore': 'Explore',
  'who_are_you_today': 'Who are you today?',
  'welcome_to_7ajemty': 'Welcome to 7ajemty',

  // Appointments
  'my_appointments': 'My Appointments',
  'upcoming': 'Upcoming',
  'history': 'History',
  // Status Badge Colors (no need to translate the keys themselves usually, but here are the texts)
  'status_pending': 'Pending',
  'status_confirmed': 'Confirmed',
  'status_in_progress': 'In Progress',
  'status_completed': 'Completed',
  'status_cancelled': 'Cancelled',
  'status_declined': 'Declined',

  // Filters
  'all': 'All',
  'filter_by_date': 'Filter by date',
  'clear_filters': 'Clear filters',

  // Appointment Details Bottom Sheet
  'appointment_details_title': 'Appointment Details',
  'date_and_time': 'Date and Time',
  'estimated_end': 'Estimated end: {0}',
  'client_label': 'Client',
  'specialist_label': 'Specialist',
  'salon_label': 'Salon',
  'services_label': 'Services',
  'no_service_selected': 'No service selected',
  'total_label': 'Total:',
  'close_btn': 'Close',
  'next_appointment': 'Next Appointment',
  'see_on_map': 'See on Map 🗺️',
  'in_time': 'In',
  'time_passed': 'Time has passed',
  'time_remaining_hours_min': '{0}h {1}min remaining',
  'time_remaining_min': '{0}min remaining',

  // Search Page
  'search_hint': 'Search for a salon, service...',
  'no_results_found': 'No results found...',
  'salon_name_default': 'Salon Name',
  'address_unavailable': 'Address unavailable',
  'search_empty_state': 'Search for a barber or service...',

  // Client Home & Appointments
  'professional_label': 'Professional: {0}',
  'category_haircut': 'Haircut',
  'category_facial': 'Facial',
  'category_kids': 'Kids',
  'review_modal_title': 'Great Haircut!',
  'review_modal_desc': 'Your appointment with {0} at \'{1}\' is finished.',
  'review_modal_question': 'Did you like the haircut?',
  'review_comment_hint': 'Leave a comment (optional)...',
  'submit_review_btn': 'Submit Review',
  'skip_btn': 'Skip',
  'no_appointments_today': 'No appointments for today.',
  'rebook': '↻ Rebook',
  'leave_review': '⭐ Leave Review',

  // Booking
  'book_appointment': 'Book Appointment',
  'choose_barber': '1. Choose your barber',
  'date_time': '2. Date & Time',
  'haircut_model': '3. Haircut Model (Optional)',
  'add_photo_gallery': 'Add photo (from gallery)',
  'photo_added_success': 'Photo added successfully',
  'confirm_appointment': 'Confirm Appointment',
  'pay_on_site': 'Pay on site',
  'appointment_confirmed': 'Appointment confirmed ✅',
  'any_barber': 'Any barber',
  'no_slots_available': 'No slots available for this day.',
  'confirm_cancel_appointment':
      'Are you sure you want to cancel the appointment?\n\n⚠️ If you cancel 3 times in a row, your account will be blocked.',
  'yes_cancel': 'Yes, Cancel',
  'go_back': 'Go Back',
  'appointment_cancelled': 'Appointment Cancelled',

  // Auth & Account
  'connect': 'Login',
  'welcome_back': 'Welcome back!',
  'forgot_password': 'Forgot password?',
  'logged_in_successfully': 'Logged in successfully!',
  'no_account_yet': 'Don\'t have an account?',
  'create_account': 'Create Account',
  'passwords_do_not_match': 'Passwords do not match',
  'all_set': 'All set 🎉',
  'creating_account_status': 'Creating account...',
  'phone_must_be_8_digits': 'Phone number must be 8 digits',
  'password_must_be_6_chars': 'Password must be at least 6 characters',
  'error_issue': 'Issue',
  'join_7jemty_enjoy_services': 'Join 7jemty and enjoy our services.',
  'i_am_salon_owner': 'I am a salon owner',
  'check_this_to_add_salon': 'Check this if you want to add your salon',
  'already_have_account': 'Already have an account?',
  'connect_action': 'Log in',
  'full_name': 'Full Name',
  'phone_number_label': 'Phone Number',
  'password_short': 'Password',
  'confirm_password_hint': 'Confirm Password',
  'field_required': 'This field is required',
  'sign_in_title': 'Sign In',
  'sign_up_title': 'Sign Up',

  // Shop & Products
  'shop': 'Shop',
  'products': 'Products',
  'search_product': 'Search for a product...',
  'category_all': 'All',
  'category_hair': 'Hair',
  'category_beard': 'Beard',
  'category_face': 'Face',
  'category_accessories': 'Accessories',
  'added_to_cart': 'Added to cart 🛒',
  'added_to_cart_success': 'Added to cart successfully 🛒',
  'add_to_cart_btn': 'Add to Cart',
  'my_cart': 'My Cart',
  'total_to_pay': 'Total to pay',
  'order_validated_successfully': 'Order placed successfully 🎉',
  'validate_order': 'Place Order',
  'your_cart_is_empty': 'Your cart is empty',
  'return_to_shop': 'Return to Shop',
  'professional_product_desc':
      'This professional product is specially designed for a perfect hold all day long. Ideal for all hair types, it leaves no residue and is easy to wash out.',
  'usage_tips': 'Usage Tips',
  'apply_on_dry_hair': 'Apply to dry or slightly damp hair.',
  'quantity_2': '2',
  'professional_salon_brand': 'Brand / Professional Salon',
  'description_title': 'Description',

  // Profile & Loyalty
  'my_profile': 'My Profile',
  'profile': 'Profile',
  'my_activities': 'My Activities',
  'product_orders': 'Product Orders',
  'favorite_salons': 'Favorite Salons',
  'settings': 'Settings',
  'settings_fr': 'Settings',
  'orders_remaining': '{0} orders remaining',
  'favorite_salons_count': '{0} salons',
  'favorites_empty_title': 'No favorite salons yet',
  'favorites_empty_subtitle':
      'Save salons you like and you will find them here quickly.',

  // Barber / Admin Salon Management
  'admin_dashboard': 'Admin Dashboard',
  'welcome_admin': 'Welcome, Admin!',
  'my_salon': 'My Salon',
  'manage_your_salon': 'Manage Your Salon',
  'create_salon_action': 'Create Salon',
  'give_salon_name_address': 'Provide a name and address for your salon.',
  'salon_created_successfully': 'Salon created successfully!',
  'my_agenda': 'My Agenda',
  'accept_btn': 'Accept',
  'reject_btn': 'Reject',
  'salon_settings': 'Salon Settings',
  'info_tab': 'Info',
  'services_tab_val': 'Services',
  'team_tab': 'Team',
  'schedule_tab': 'Schedule',
  'photos_tab': 'Photos',
  'manage_team': 'Manage Team',
  'new_specialist': 'New Specialist',
  'opening_time': 'Opening Hours',
  'upload_photo': 'Upload Photo',
  'appointments_short': 'My Appts',
  'setup_salon': 'Set Up Your Salon',
  'salon_identity': 'Salon Identity',
  'salon_identity_desc':
      'Provide basic information for your salon so clients can find it easily.',
  'salon_name_req': 'Salon Name *',
  'salon_name_hint': 'e.g. Barbershop VIP',
  'salon_name_validation': 'Salon name is required',
  'address_req': 'Full Address *',
  'address_hint': 'e.g. 12 Habib Bourguiba Street, Tunis',
  'address_validation': 'Valid address is required',
  'google_maps_optional': 'Google Maps Link (Optional)',
  'google_maps_hint': 'Paste map link here',
  'speciality_optional': 'Specialty (Optional)',
  'speciality_hint': 'e.g. Haircut, Beauty...',
  'presentation_optional': 'Presentation (Optional)',
  'presentation_desc': 'Provide more details to attract more clients.',
  'description_label': 'Description',
  'description_hint': 'What are your services and vibe?',
  'contact_phone': 'Contact Number',
  'contact_phone_hint': 'Phone number',
  'website_label': 'Website',
  'website_hint': 'https://www.my-salon.com',
  'skip_step': 'Skip step',
  'cover_photo': 'Cover Photo',
  'cover_photo_desc': 'An attractive photo for your salon will draw clients.',
  'upload_photo_prompt': 'Tap here to upload a photo',
  'or_use_link': 'Or use a link',
  'use_url': 'Use URL',
  'finish': 'Finish',
  'salon_created_success_title': 'Congratulations! 🎉',
  'salon_created_success_desc': 'Your salon has been set up successfully.',
  'updating': 'Updating...',
  'updated_l': 'Updated to',
  'finished_haircut_q': 'Finished the haircut?',
  'app_name_7jemty': '7jemty',
  'salon_name_label': 'Salon Name',
  'no_salon_found': 'No salon found.',
  'create_your_salon': 'Create your salon',
  'reload_btn': 'Reload',
  'about_salon': 'About the Salon',
  'contact_label': 'Contact',
  'your_services_will_appear_here': 'Your services will appear here',
  'no_client_reviews': 'No client reviews yet.',
  'saving_status': 'Saving...',
  'saved_successfully': 'Saved successfully 🎉',
  'l_prefix': 'L',
  'specialist_added': 'Specialist added 🎉',
  'specialist_updated': 'Specialist updated',
  'specialist_deleted': 'Specialist removed',
  'save_everything': 'Save Everything',
  'general_info': 'General Information',
  'services_management': 'Services Management (Coming soon)',
  'tab_services': 'Services',
  'add_new_service': 'Add Service',
  'save_service': 'Save Service',
  'edit_service': 'Edit Service',
  'update_service': 'Update Service',
  'service_added': 'Service added 🎉',
  'service_updated': 'Service updated',
  'service_deleted': 'Service deleted',
  'delete_service_confirm_title': 'Delete Service?',
  'delete_service_confirm_desc': 'Are you sure you want to delete service {0}?',
  'service_name': 'Service Name',
  'service_name_hint': 'Ex: Fade haircut',
  'price_tnd': 'Price (TND)',
  'price_hint': 'Ex: 20',
  'duration_hint': 'Ex: 30',
  'name_price_time_required': 'Name, price and duration are required',
  'no_data_found': 'No data found',
  'url_label': 'URL',
  'upload_from_gallery': 'Gallery',
  'image_optional': 'Image (optional)',
  'or_put_image_url': 'Or paste image URL',
  'cancel_action_2': 'Cancel',
  'no_specialist_added': 'No specialist added yet',
  'edit_specialist': 'Edit Specialist',
  'update_specialist': 'Update Specialist',
  'name_phone_required': 'Name and phone are required',
  'delete_specialist_confirm_title': 'Delete Specialist?',
  'delete_specialist_confirm_desc':
      'Are you sure you want to remove {0} from your team?',
  'time_09_00': '09:00 AM',
  'empty_text': 'to',
  'time_06_00': '06:00 PM',
  'salon_photos': 'Salon Photos',
  'add_salon_photos': 'ADD SALON PHOTOS',
  'download_photo': 'Download Photo',
  'new_photo': 'NEW PHOTO',
  'barber_space': 'Barber Space',
  'barber_space_wip': 'This is the barber space (Work in progress...)',

  // Super Admin
  'total_users': 'Total Users',
  'total_salons': 'Total Salons',
  'pending_approvals': 'Pending Approvals',
  'system_overview': 'System Overview',
  'administrative_actions': 'Administrative Actions',
  'manage_users': 'Manage Users',
  'users_management_desc': 'View and manage platform users',
  'manage_salons': 'Manage Salons',
  'salons_management_desc': 'Approve or suspend salons',
  'delete_user_q': 'Delete User?',
  'delete_user_desc':
      'Are you sure you want to delete this user? This action cannot be undone.',
  'delete_salon_confirm': 'Delete Salon?',
  'delete_salon_warning':
      'This will permanently delete the salon and all its data.',
  'peek_view': 'Peek View',
  'approve': 'Approve',
  'suspend': 'Suspend',
  'reactivate': 'Reactivate',
  'admin_profile_desc': 'Manage your personal information',

  // Tabs & Details
  'tab_details': 'Details',
  'tab_specialist': 'Specialists',
  'tab_review': 'Reviews',
  'services': 'Services',
  'tab_appointments': 'Appointments',

  // Status & Badges
  'open_status': 'Open',
  'opened_status': 'Opened',
  'zero_reviews': '(0 reviews)',
  'verified_status': 'Verified',
  'status_active': 'Status: Active',
  'starting_from': 'Starting from...',
  'no_reviews_yet': 'No reviews yet',
  'tab_reviews': 'Reviews',

  // Action Buttons
  'reserve_btn': 'Book Now',
  'see_all_btn': 'See All',
  'renew_btn': 'Renew',

  // Other Missing Translations
  'date_example': '📅 24 Feb - 14:00',
  'barber_king_name': 'Barber King 👑',
  'haircut_beard_price': 'Haircut + Beard - 25 DT',
  'barber_sami': 'Barber: Sami',
  'directions': 'Directions',
  'attention': 'Attention',

  // System & Messages
  'status_updated': 'Status updated: {0}',
  'error_updating_status': 'Error during update',
  'product_added_to_cart': '{0} added! 🛒',
  'url_hint': 'https://...',
  'review_experience_hint': 'Tell us about your experience...',
  'error_with_message': 'Error: {0}',
  'sms_code_sent': 'A code has been sent via SMS.',
  'code_must_be_6_digits': 'The code must contain exactly 6 digits.',
  'account_verified_success':
      'Your account has been verified and created successfully.',

  // Admin Space
  'edit_user_profile': 'Edit User & Profile',
  'verified_label': 'Verified',
  'speciality_title_label': 'Speciality Title',
  'bio_label': 'Bio',
  'edit_salon_info': 'Edit Salon Info',
  'no_data_available': 'No data available.',
  'coupes_count': '{0} cuts',

  // Booking Flow
  'book_appointment_for': 'Book for: {0}',
  'choose_your_services': 'Choose your services',
  'no_service_available': 'No services available',
  'duration_min': '{0} min',
  'choose_professional_title': 'Choose professional',
  'unknown': 'Unknown',
  'no_professional_found_update': 'No professional found.',
  'date_and_time_step': 'Date and time',
  'select_at_least_one_service': 'Select at least one service',
  'select_barber_validation': 'Please select a professional',
  'select_time_validation': 'Please select a time slot',
  'login_to_book': 'Login to book',
  'phone_number': 'Phone number',
  'password': 'Password',
  'login': 'Login',
  'next': 'Next',
  'welcome_exclamation': 'Welcome!',
  'booking_error_title': 'Booking Error',
  'error_loading_salon_details': 'Error loading salon details',
  'booking_created_success': 'Your booking was successful!',

  // Admin Labels
  'full_name_label': 'Full Name',
  'phone_label': 'Phone',
  'email_label': 'Email',
  'speciality_label': 'Speciality',
  'contact_phone_label': 'Contact Phone',
  'address_label': 'Address',
  'congratulations': 'Congratulations!',
  'appointment_with_ahmed_finished':
      'Your appointment with Ahmed at \'Barbershop VIP\' has finished.',
  'did_you_like_haircut': 'Did you like the haircut?',
  'review_sent_thank_you': 'Review sent successfully! Thank you 🎉',
  'send_review': 'Send Review',
  'skip': 'Skip',
  'city_ariana_tunis': 'Ariana, Tunis',
  'dynamic_today_time': 'Today, {0}',
  'opening_map': 'Opening map 🗺️',
  'see_on_map_action': 'See on map 🗺️',
  'today_15_00': 'Today, 15:00',
  'barber_king_haircut': 'Barber King - Haircut + Beard',
  'remaining_2h_30min': '2h 30min remaining',
  'status_confirmed_badge': 'Confirmed',
  'reserved': 'Reserved',
  'sami_name': 'Sami',
  'sami_email': 'sami@gmail.com',
  'tunisian_lang': 'Tunisian',
  'english_lang_title': 'English',
  'redirecting_to_reservation': 'Redirecting to reservation...',
  'reserve_this_style': 'Reserve this style',
  'rate_this_salon': 'Rate this salon',
  'thank_you_for_review': 'Thank you for your review! ⭐',
  'send_the_review': 'Send the review',
  'rating_4_9': '4.9',
  'based_on_120_reviews': 'Based on 120 reviews',
  'write_a_review': 'Write a review',
  'address_ariana': 'Habib Bourguiba Avenue, Ariana',
  'reviews_120': ' (120 reviews)',
  'added_info_successfully': 'Information added successfully',
  'other_details': 'Other details',
  'do_it_later': 'Do it later',
  'few_details_left': 'Just a few details left',
  'add_description_number':
      'Add description and number to reach more clients (Optional).',
  'save_info': 'Save Information',
  'skip_this_step': 'Skip this step',
  'all_appointments': 'All Appointments',
  'my_calendar': 'My Calendar',
  'hello_test': 'hello test monta',
  'appointments_today_fr': 'Appts Today',
  'no_appointments_today_fr': 'You have no appointments for today.',
  'quick_access_menu': 'Quick Access',
  'upcoming_appointments_fr': 'Upcoming Appointments',
  'today_appointments_title': 'Today\'s Appointments',
  'subscription_title': 'Subscription',
  'number_four': '4',
  'remaining_appointments': 'Remaining DB appts',
  'el_baze_barberia': 'EL BAZE BARBERIA',
  'haircut_history': 'Haircut History',
  'subscription_status': 'Subscription Status',
  'premium_tier': 'PREMIUM',
  'unknown_salon': 'Unknown salon',
  'unassigned_professional': 'Unassigned Barber',
  'professional': 'Professional',
  'thank_you': 'Thank you!',
  'review_added_success': 'Review added successfully.',
  'error': 'Error',
  'please_select_rating': 'Please select a rating.',
  'your_comment_optional': 'Your comment (Optional)',
  'send': 'Send',
  'decline_btn': 'Decline',
  'status_rebooked': 'Rebooked',
};
