const Map<String, String> en = {
      // General
      'home': 'Home',
      'language': 'Language',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'terms': 'Terms & Conditions',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'confirm': 'Confirm',

      // Client Home Page
      'search_placeholder': 'Search for salon, service...',
      'greeting': 'Hello 👋',
      'top_categories': 'Quick Categories',
      'near_you': 'Near You',
      'top_rated': 'Top Rated Salons 👑',

      // Appointments
      'my_appointments': 'My Appointments',
      'upcoming': 'Upcoming',
      'history': 'History',
      'next_appointment': 'Next Appointment',
      'see_on_map': 'See on Map 🗺️',
      'in_time': 'In',
      'status_confirmed': 'Confirmed',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'status_in_progress': 'In Progress',
      'status_pending': 'Pending',
      'time_passed': 'Time has passed',
      'time_remaining_hours_min': '{0}h {1}min remaining',
      'time_remaining_min': '{0}min remaining',

      // Booking
      'book_appointment': 'Book Appointment',
      'choose_barber': '1. Choose your barber',
      'date_time': '2. Date & Time',
      'haircut_model': '3. Haircut Model (Optional)',
      'add_photo_gallery': 'Add photo (from gallery)',
      'photo_added_success': 'Photo added successfully',
      'confirm_appointment': 'Confirm Appointment',
      'pay_on_site': 'Pay on site',
      'appointment_confirmed': 'Appointment confirmed ✅',
      'any_barber': 'Any barber',

      // Profile
      'my_profile': 'My Profile',
      'loyalty_cards': 'Loyalty Cards 🎁',
      'my_activities': 'My Activities',
      'product_orders': 'Product Orders',
      'favorite_salons': 'Favorite Salons',
      'settings': 'Settings',
      'shop': 'Shop',
      'appointments_short': 'My Appointments',
      'products': 'Products',
      'profile': 'Profile',
      'search_product': 'Search a product...',
      'category_all': 'All',
      'category_hair': 'Hair',
      'category_beard': 'Beard',
      'category_face': 'Face',
      'category_accessories': 'Accessories',
      'added_to_cart': 'added to cart 🛒',
      'admin_dashboard': 'Admin Dashboard',
      'welcome_admin': 'Bienvenue Admin!',
      'connect': 'Connecti',
      'welcome_back': 'Marhba bik marra okhra !',
      'forgot_password': 'Nsitt l\'mot de passe ?',
      'logged_in_successfully': 'Dkholt mriguel !',
      'no_account_yet': 'Ma aandekch compte ? ',
      'create_account': 'Aamel compte',
      'passwords_do_not_match': 'Mot de passe mouch kif kif',
      'all_set': 'Jawwek mriguel 🎉',
      'error_issue': 'Mochkla',
      'join_7jemty_enjoy_services':
          'Idkhol l 7jemty w temtaa b les services mteana.',
      'i_am_salon_owner': 'Ena moulé salon (Patron)',
      'check_this_to_add_salon': 'Cochi hethi ken theb tzid salon mte3ek',
      'already_have_account': 'Aandek compte deja ? ',
      'leave_review': '⭐ leave review',
      'rebook': '↻ Rebook',
      'date_example': '📅 24 Fév - 14:00',
      'barber_king_name': 'Barber King 👑',
      'haircut_beard_price': 'Hjema + Lihya - 25 DT',
      'barber_sami': 'Hajem: Sami',
      'directions': 'Thneya',
      'attention': 'Rod belek',
      'confirm_cancel_appointment':
          'Are you sure you want to cancel the appointment?\n\n⚠️ If you cancel 3 times in a row, your account will be blocked.',
      'go_back': 'Go Back',
      'appointment_cancelled': 'Appointment Cancelled',
      'yes_cancel': 'Ey, Batel',
      'congratulations': 'Sa77atoulek!',
      'appointment_with_ahmed_finished':
          'Your appointment with Ahmed at \'Barbershop VIP\' is completed.',
      'did_you_like_haircut': 'Did you like the haircut?',
      'review_sent_thank_you': 'Review sent successfully! Thank you 🎉',
      'send_review': 'Abaath l\'avis',
      'skip': 'Fout',
      'city_ariana_tunis': 'Ariana, Tunis',
      'opening_map': 'Kaaed yhel fel map 🗺️',
      'see_on_map_action': 'Chouf fil map 🗺️',
      'today_15_00': 'Lyoum, 15:00',
      'barber_king_haircut': 'Barber King - Coupe Cheveux + Barbe',
      'remaining_2h_30min': '2h 30min remaining',
      'status_confirmed_badge': 'Confirmed',
      'reserved': 'Resservi',
      'my_cart': 'Mon Panier',
      'total_to_pay': 'Total à payer',
      'order_validated_successfully': 'Commande validée avec succès 🎉',
      'validate_order': 'Valider la commande',
      'your_cart_is_empty': 'Votre panier est vide',
      'return_to_shop': 'Retourner à la boutique',
      'quantity_2': '2',
      'professional_salon_brand': 'Marque / Salon Professionnel',
      'description_title': 'Description',
      'professional_product_desc':
          'Ce produit professionnel est spécialement conçu pour offrir une tenue parfaite tout au long de la journée. Idéal pour tous les types de cheveux, il ne laisse pas de résidus et se lave facilement.',
      'usage_tips': 'Conseils d\'utilisation',
      'apply_on_dry_hair': 'Appliquer sur cheveux secs ou légèrement humides.',
      'added_to_cart_success': 'Ajouté au panier avec succès 🛒',
      'add_to_cart_btn': 'Ajouter au panier',
      'sami_name': 'Sami',
      'sami_email': 'sami@gmail.com',
      'tunisian_lang': 'Tounsi',
      'english_lang_title': 'English',
      'redirecting_to_reservation': 'Redirection vers la réservation...',
      'reserve_this_style': 'Réserver ce style',
      'rate_this_salon': 'Notez ce salon',
      'thank_you_for_review': 'Merci pour votre avis ! ⭐',
      'send_the_review': 'Envoyer l\'avis',
      'rating_4_9': '4.9',
      'based_on_120_reviews': 'Basé sur 120 avis',
      'write_a_review': 'Écrire un avis',
      'open_status': 'Ouvert',
      'address_ariana': 'Avenue Habib Bourguiba, Ariana',
      'reviews_120': ' (120 avis)',
      'reserve_btn': 'Réserver',
      'added_info_successfully': 'Zidna les infos mriguel',
      'other_details': 'Tafasil okhra',
      'do_it_later': 'Baadin',
      'few_details_left': 'Mazzal chwaya tafasil',
      'add_description_number':
          'Zid description w nemrou bech tzid tjib les clients (Optionnel).',
      'save_info': 'Sajel les infos',
      'skip_this_step': 'Fout l\'etape hethi',
      'congrats': 'Mabrouk! 🎉',
      'salon_created_successfully': 'Salon mte3ek thal mriguel',
      'my_salon': 'Salon mte3i',
      'manage_your_salon': 'Riguel Salon mte3ek',
      'give_salon_name_address': 'Aati esm w adresse l salon mte3ek.',
      'create_salon_action': 'Aamel salon',
      'updating': 'Kaad ybadal...',
      'updated_l': 'Badalna l',
      'my_agenda': 'Agenda mte3i',
      'no_appointments_today': 'Ma famma hatta rendez-vous lyoum.',
      'reject_btn': 'Orfodh',
      'accept_btn': 'Ikbel',
      'finished_haircut_q': 'Kmalt l\'hjema ?',
      'app_name_7jemty': '7jemty',
      'salon_name_label': 'Esm Salon',
      'no_salon_found': 'Ma famma hatta salon.',
      'create_your_salon': 'Aamel salon mte3ek',
      'reload_btn': 'Aawed chargi',
      'opened_status': 'Mahloul',
      'zero_reviews': '(0 avis)',
      'about_salon': 'Aal salon',
      'contact_label': 'Contact',
      'your_services_will_appear_here':
          'Les services mte3ek bech yodh\'hrou houni',
      'no_client_reviews': 'Ma famma hatta avis mtaa client tawa.',
      'error_title': 'Erreur',
      'saving_status': 'Kaad ysajjel...',
      'saved_successfully': 'Tsayyev mriguel 🎉',
      'l_prefix': 'L',
      'creating_account_status': 'Kaad yasnaa fi compte...',
      'specialist_added': 'Zadna specialiste 🎉',
      'salon_settings': 'Parametres mtaa salon',
      'save_everything': 'Sajjel kol chay',
      'info_tab': 'Info',
      'services_tab_val': 'Services',
      'team_tab': 'Equipe',
      'schedule_tab': 'Wakt',
      'photos_tab': 'Tsawer',
      'general_info': 'General Information',
      'services_management': 'Services Management (Pending)',
      'manage_team': 'Manage Team',
      'new_specialist': 'NEW SPECIALIST',
      'url_label': 'URL',
      'upload_photo': 'uploadi taswira',
      'save_btn': 'Sajjel',
      'cancel_action_2': 'Batel',
      'no_specialist_added': 'Ma zadet hatta specialiste',
      'opening_time': 'Wakt lhallen',
      'time_09_00': '09:00 AM',
      'empty_text': 'à',
      'time_06_00': '06:00 PM',
      'salon_photos': 'Tsawer el salon',
      'add_salon_photos': 'ZID TSARWER LEL SALON',
      'download_photo': 'Techargi taswira',
      'new_photo': 'TASWIRA JDIDA',
      'all_appointments': 'Tous les Rendez-vous',
      'my_calendar': 'Mon Calendrier',
      'hello_test': 'hello  test monta',
      'appointments_today_fr': 'RDV Aujourd',
      'information_title': 'Information',
      'no_appointments_today_fr':
          'Vous n\'avez aucun rendez-vous pour aujourd\'hui.',
      'ok_btn': 'OK',
      'quick_access_menu': 'Quick Access',
      'upcoming_appointments_fr': 'Prochains Rendez-vous',
      'welcome_to_7ajemty': 'Mar7ba bik fi 7ajamty',
      'who_are_you_today': 'Chkoun enti lyoum?',
      'barber_space': 'Espace 7ajem',
      'barber_space_wip': 'Hetha l\'espace mta3 l\'7ajem (En cours de dev...)',
      'today_appointments_title': 'Rendez-vous d\'aujourd\'hui',
      'subscription_title': 'Abonnement',
      'status_active': 'Statut: Actif',
      'number_four': '4',
      'remaining_appointments': 'RDV restants',
      'renew_btn': 'Renouveler',
      'loyalty_points': 'Points Fidélité',
      'points_1200': 'Points: 1200',
      'next_reward_2800': 'Prochaine récompense: 2800 pts',
      'el_baze_barberia': 'EL BAZE BARBERIA',
      'verified_status': 'Vérifié',
      'close_btn': 'Fermer',
      'my_points': 'Mes Points',
      'total_1200_points': 'Total: 1200 pts',
      'haircut_history': 'Historique des Coupes',
      'see_all_btn': 'Voir tout',
      'settings_fr': 'Paramètres',
      'subscription_status': 'Statut Abonnement',
      'premium_tier': 'PREMIUM',
      'phone_must_be_8_digits': 'Phone number must be 8 digits',
      'password_must_be_6_chars': 'Password must be at least 6 characters',
      'no_slots_available': 'No slots available for this day.',
      'tab_appointments': 'Rendez-vous',
    };
