const Map<String, String> tn = {
  // General
  'home': 'Accueil',
  'language': 'Lougha',
  'notifications': 'Notificatiounet',
  'help_support': 'Mo3awna',
  'terms': 'A7kem amma',
  'logout': 'Okhrej',
  'cancel': 'Batel',
  'confirm': 'Aked',

  // Client Home Page
  'search_placeholder': 'Lawej aala salon, service...',
  'greeting': 'Ahla 👋',
  'top_categories': 'Chnowa tawa?',
  'near_you': '9rab lik',
  'top_rated': 'A7sen les Salons 👑',

  // Appointments
  'my_appointments': 'Rendez-vous Mte3i',
  'upcoming': 'Jeyin',
  'history': 'Lqdom',
  'next_appointment': 'Rendez-vous jey',
  'see_on_map': 'Chouf fil map 🗺️',
  'in_time': 'Mazel',
  'status_confirmed': 'M\'akd',
  'status_completed': 'Kmal',
  'status_cancelled': 'Tbatel',
  'status_in_progress': 'Fi wosst',
  'status_pending': 'Mazel',
  'status_declined': 'Morfoudh',
  'time_passed': 'L\'wa9t r7el',
  'time_remaining_hours_min': 'Mazal {0}h {1}min',
  'time_remaining_min': 'Mazal {0}min',

  // Filters
  'all': 'Lkol',
  'filter_by_date': 'Filtri b tari5',
  'clear_filters': 'Nadhaf les filtres',

  // Booking
  'book_appointment': 'A7jez RDV',
  'choose_barber': '1. Ekhtar l\'hajem mte3ek',
  'date_time': '2. Nharetha wel wa9t',
  'haircut_model': '3. Modele mtaa hjema (Optionnel)',
  'add_photo_gallery': 'Zid taswira (mel galerie)',
  'photo_added_success': 'Taswira tzadit mriguel',
  'confirm_appointment': 'Confirmer le Rendez-vous',
  'pay_on_site': 'Khalles sur place',
  'appointment_confirmed': 'Rendez-vous t\'aked ✅',
  'any_barber': 'Ay wahed',

  // Profile
  'my_profile': 'Profil Mte3i',
  'loyalty_cards': 'Kwaret Fidélité 🎁',
  'my_activities': 'Activités Mte3i',
  'product_orders': 'Comandeti mtaa Produits',
  'favorite_salons': 'Salouneti l\'Favoris',
  'settings': 'Parametres',
  'shop': 'Boutique',
  'appointments_short': 'RDV Mte3i',
  'products': 'Produits',
  'profile': 'Profil',
  'search_product': 'Lawwej 3la produit...',
  'category_all': 'Kol',
  'category_hair': 'Cha3r',
  'category_beard': 'Le7ya',
  'category_face': 'Wajh',
  'category_accessories': 'Accessoires',
  'added_to_cart': 'tzed lel panier 🛒',
  'admin_dashboard': 'Admin Dashboard',
  'welcome_admin': 'Bienvenue Admin!',
  'connect': 'Connecti',
  'welcome_back': 'Marhba bik marra okhra !',
  'forgot_password': 'Nsitt l\'mot de passe ?',
  'logged_in_successfully': 'Dkholt mriguel !',
  'no_account_yet': 'Ma aandekch compte ? ',
  'create_account': 'Aamel compte',
  'passwords_do_not_match': 'Mot de passe mouch kif kif',
  'all_set': 'Jawwek mriguel 🎉',
  'error_issue': 'Mochkla',
  'join_7jemty_enjoy_services':
      'Idkhol l 7jemty w temtaa b les services mteana.',
  'i_am_salon_owner': 'Ena moulé salon (Patron)',
  'check_this_to_add_salon': 'Cochi hethi ken theb tzid salon mte3ek',
  'already_have_account': 'Aandek compte deja ?',
  'connect_action': 'Connecter',
  'full_name': 'Esmek l\'kemel',
  'phone_number_label': 'Numrou Tlifoun',
  'password_short': 'Mot de passe',
  'confirm_password_hint': 'Aawed l\'mot de passe',
  'field_required': 'Hedha lezem taamrou',
  'sign_in_title': 'Connecti',
  'sign_up_title': 'Aamel compte',
  'leave_review': '⭐ Khali avis',
  'rebook': '↻ Aawed Ahjez',
  'date_example': '📅 24 Fév - 14:00',
  'barber_king_name': 'Barber King 👑',
  'haircut_beard_price': 'Hjema + Lihya - 25 DT',
  'barber_sami': 'Hajem: Sami',
  'directions': 'Thneya',
  'attention': 'Rod belek',
  'confirm_cancel_appointment':
      'Met\'aked theb tbatel e-rendez-vous?\n\n⚠️ Kan tbatel 3 marrat wra baadhom comptek yetbloka.',
  'go_back': 'Rjou3',
  'appointment_cancelled': 'Rendez-vous tbatel',
  'yes_cancel': 'Ey, Batel',
  'congratulations': 'Sa77atoulek!',
  'appointment_with_ahmed_finished':
      'Rendez-vous mte3ek maa Ahmed fi salon \'Barbershop VIP\' kmal.',
  'did_you_like_haircut': '3jebtek l7jema?',
  'review_sent_thank_you': 'Avis tbaath mriguel! Aaychek 🎉',
  'send_review': 'Abaath l\'avis',
  'skip': 'Fout',
  'city_ariana_tunis': 'Ariana, Tunis',
  'dynamic_today_time': 'Lyoum, {0}',
  'opening_map': 'Kaaed yhel fel map 🗺️',
  'see_on_map_action': 'Chouf fil map 🗺️',
  'today_15_00': 'Lyoum, 15:00',
  'barber_king_haircut': 'Barber King - Coupe Cheveux + Barbe',
  'remaining_2h_30min': 'Mazel 2h 30min',
  'status_confirmed_badge': 'M\'akd',
  'reserved': 'Resservi',
  'my_cart': 'Mon Panier',
  'total_to_pay': 'Total à payer',
  'order_validated_successfully': 'Commande validée avec succès 🎉',
  'validate_order': 'Valider la commande',
  'your_cart_is_empty': 'Votre panier est vide',
  'return_to_shop': 'Retourner à la boutique',
  'quantity_2': '2',
  'professional_salon_brand': 'Marque / Salon Professionnel',
  'description_title': 'Description',
  'professional_product_desc':
      'Ce produit professionnel est spécialement conçu pour offrir une tenue parfaite tout au long de la journée. Idéal pour tous les types de cheveux, il ne laisse pas de résidus et se lave facilement.',
  'usage_tips': 'Conseils d\'utilisation',
  'apply_on_dry_hair': 'Appliquer sur cheveux secs ou légèrement humides.',
  'added_to_cart_success': 'Ajouté au panier avec succès 🛒',
  'add_to_cart_btn': 'Ajouter au panier',
  'sami_name': 'Sami',
  'sami_email': 'sami@gmail.com',
  'tunisian_lang': 'Tounsi',
  'english_lang_title': 'English',
  'redirecting_to_reservation': 'Redirection vers la réservation...',
  'reserve_this_style': 'Réserver ce style',
  'rate_this_salon': 'Notez ce salon',
  'thank_you_for_review': 'Merci pour votre avis ! ⭐',
  'send_the_review': 'Envoyer l\'avis',
  'rating_4_9': '4.9',
  'based_on_120_reviews': 'Basé sur 120 avis',
  'write_a_review': 'Écrire un avis',
  'open_status': 'Ouvert',
  'address_ariana': 'Avenue Habib Bourguiba, Ariana',
  'reviews_120': ' (120 avis)',
  'reserve_btn': 'Réserver',
  'starting_from': 'A partir de...',
  'no_reviews_yet': 'Ma famma 7ata avis tawa.',
  'tab_reviews': 'Avis',
  'added_info_successfully': 'Zidna les infos mriguel',
  'other_details': 'Tafasil okhra',
  'do_it_later': 'Baadin',
  'few_details_left': 'Mazzal chwaya tafasil',
  'add_description_number':
      'Zid description w nemrou bech tzid tjib les clients (Optionnel).',
  'save_info': 'Sajel les infos',
  'skip_this_step': 'Fout l\'etape hethi',
  'congrats': 'Mabrouk! 🎉',
  'salon_created_successfully': 'Salon mte3ek thal mriguel',
  'my_salon': 'Salon mte3i',
  'manage_your_salon': 'Riguel Salon mte3ek',
  'give_salon_name_address': 'Aati esm w adresse l salon mte3ek.',
  'create_salon_action': 'Aamel salon',
  'updating': 'Kaad ybadal...',
  'updated_l': 'Badalna l',
  'my_agenda': 'Agenda mte3i',
  'no_appointments_today': 'Ma famma hatta rendez-vous lyoum.',
  'reject_btn': 'Orfodh',
  'accept_btn': 'Ikbel',
  'finished_haircut_q': 'Kmalt l\'hjema ?',
  'app_name_7jemty': '7jemty',
  'salon_name_label': 'Esm Salon',
  'no_salon_found': 'Ma famma hatta salon.',
  'create_your_salon': 'Aamel salon mte3ek',
  'reload_btn': 'Aawed chargi',
  'opened_status': 'Mahloul',
  'zero_reviews': '(0 avis)',
  'about_salon': 'Aal salon',
  'contact_label': 'Contact',
  'your_services_will_appear_here': 'Les services mte3ek bech yodh\'hrou houni',
  'no_client_reviews': 'Ma famma hatta avis mtaa client tawa.',
  'error_title': 'Erreur',
  'saving_status': 'Kaad ysajjel...',
  'saved_successfully': 'Tsayyev mriguel 🎉',
  'l_prefix': 'L',
  'creating_account_status': 'Kaad yasnaa fi compte...',
  'specialist_added': 'Zadna specialiste 🎉',
  'salon_settings': 'Parametres mtaa salon',
  'save_everything': 'Sajjel kol chay',
  'info_tab': 'Info',
  'services_tab_val': 'Services',
  'team_tab': 'Equipe',
  'schedule_tab': 'Wakt',
  'photos_tab': 'Tsawer',
  'general_info': 'Maaloumet aamma',
  'services_management': 'Gestion mtaa les services (Mazel)',
  'manage_team': 'Riguel l\'equipe',
  'new_specialist': 'SPECIALISTE JDID',
  'url_label': 'URL',
  'upload_photo': 'uploadi taswira',
  'save_btn': 'Sajjel',
  'cancel_action_2': 'Batel',
  'no_specialist_added': 'Ma zadet hatta specialiste',
  'opening_time': 'Wakt lhallen',
  'time_09_00': '09:00 AM',
  'empty_text': 'à',
  'time_06_00': '06:00 PM',
  'salon_photos': 'Tsawer el salon',
  'add_salon_photos': 'ZID TSARWER LEL SALON',
  'download_photo': 'Techargi taswira',
  'new_photo': 'TASWIRA JDIDA',
  'all_appointments': 'Tous les Rendez-vous',
  'my_calendar': 'Mon Calendrier',
  'hello_test': 'hello  test monta',
  'appointments_today_fr': 'RDV Aujourd',
  'information_title': 'Information',
  'no_appointments_today_fr':
      'Vous n\'avez aucun rendez-vous pour aujourd\'hui.',
  'ok_btn': 'OK',
  'quick_access_menu': 'Quick Access',
  'upcoming_appointments_fr': 'Prochains Rendez-vous',
  'welcome_to_7ajemty': 'Mar7ba bik fi 7ajamty',
  'who_are_you_today': 'Chkoun enti lyoum?',
  'barber_space': 'Espace 7ajem',
  'barber_space_wip': 'Hetha l\'espace mta3 l\'7ajem (En cours de dev...)',
  'today_appointments_title': 'Rendez-vous d\'aujourd\'hui',
  'subscription_title': 'Abonnement',
  'status_active': 'Statut: Actif',
  'number_four': '4',
  'remaining_appointments': 'RDV restants',
  'renew_btn': 'Renouveler',
  'loyalty_points': 'Points Fidélité',
  'points_1200': 'Points: 1200',
  'next_reward_2800': 'Prochaine récompense: 2800 pts',
  'el_baze_barberia': 'EL BAZE BARBERIA',
  'verified_status': 'Vérifié',
  'my_points': 'Mes Points',
  'total_1200_points': 'Total: 1200 pts',
  'haircut_history': 'Historique des Coupes',
  'see_all_btn': 'Voir tout',
  'settings_fr': 'Paramètres',
  'subscription_status': 'Statut Abonnement',
  'premium_tier': 'PREMIUM',
  'phone_must_be_8_digits': 'El nemrou yelzem ykoun mtaa 8 ar9am',
  'password_must_be_6_chars':
      'El mot de passe yelzem ykoun fih au moins 6 hrouf',
  'no_slots_available': 'Ma famma hatta wa9t feragh lyoum.',
  'tab_appointments': 'روندي فو',
  'no_professional_found_update': 'Ma famma hatta hajem. Riguel salon mte3ek.',
  'unknown': 'Inconnu',
  'total': 'Total',
  'unknown_salon': 'Salon inconnu',
  'unassigned_professional': 'Hajem mouch mawjoud',
  'professional': 'Hajem',
  'thank_you': 'Aychek!',
  'review_added_success': 'L\'avis mte3ek tzad mriguel.',
  'error': 'Ghalta',
  'please_select_rating': 'Aman ekhtar note.',
  'your_comment_optional': 'Taali9ek (Ken theb)',
  'send': 'Ab3ath',
  'setup_salon': 'Riguel Salon mte3ek',
  'salon_identity': 'Identité du salon',
  'salon_identity_desc':
      'Hatt les infos de base mtaa el salon mte3ek bech les clients yal9aweh bshoula.',
  'salon_name_req': 'Esm Salon *',
  'salon_name_hint': 'ex: Barbershop VIP',
  'salon_name_validation': 'Esem e-salon lezem',
  'address_req': 'Adresse complète *',
  'address_hint': 'ex: 12 Rue Habib Bourguiba, Tunis',
  'address_validation': 'L\'adresse lezem tkon s7i7a',
  'google_maps_optional': 'Lien Google Maps (Optionnel)',
  'google_maps_hint': 'Copie le lien mel Maps w hatou lenna',
  'speciality_optional': 'Spécialité (Optionnel)',
  'speciality_hint': 'ex: Coiffure, Esthétique...',
  'presentation_optional': 'Présentation (Optionnel)',
  'presentation_desc': 'A3ti aktar tafasil bech tjib aktar clients.',
  'description_label': 'Description',
  'description_hint': 'Chneya les services w el jaw fel salon?',
  'contact_phone': 'Numéro de contact',
  'contact_phone_hint': 'Numrou tlifoun',
  'website_label': 'Site web',
  'website_hint': 'https://www.mon-salon.com',
  'skip_step': 'Fout l\'etape',
  'cover_photo': 'Photo de couverture',
  'cover_photo_desc': 'Taswira mezyena ll salon mte3ek tzid ml iqbal.',
  'upload_photo_prompt': 'Nzel lena bech tplodi taswira',
  'or_use_link': 'Wala aamel lien',
  'use_url': 'Astaa\'mel URL',
  'finish': 'Terminer',
  'salon_created_success_title': 'Mabrouk! 🎉',
  'salon_created_success_desc': 'Salon mte3ek thal mriguel',
  'total_users': 'el users Kol ',
  'total_salons': 'e salonet Kol ',
  'pending_approvals': 'Salonet mazalou mouch approuvi',
  'system_overview': 'Chnowa fama jdid',
  'administrative_actions': 'Administrative Actions',
  'manage_users': 'Riguel el users',
  'users_management_desc': 'Chouf wala faskh el users',
  'manage_salons': 'Riguel el salonet',
  'salons_management_desc': 'Approuvi wala suspendi el salonet',
  'delete_user_q': 'Tfassakh el user?',
  'delete_user_desc': 'Met\'aked theb tfassakh hal user? Maatesh tarjaa fiha.',
  'delete_salon_confirm': 'Tfassakh el salon?',
  'delete_salon_warning':
      'Hethyya bech tfassakh kol chay mtaa el salon lel abed.',
  'peek_view': 'T\'atalla3 / Peek',
  'approve': 'Approuvi',
  'suspend': 'Suspendi',
  'reactivate': 'Raja3 khedem',
  'admin_profile_desc': 'Riguel el information personelle mte3ek',
  'orders_remaining': 'Mazzalou {0} commandes',
  'favorite_salons_count': '{0} salonet',

  // Appointment Details Bottom Sheet
  'appointment_details_title': 'Détails du Rendez-vous',
  'date_and_time': 'Date et Heure',
  'estimated_end': 'Fin estimée: {0}',
  'client_label': 'Client',
  'specialist_label': 'Spécialiste',
  'salon_label': 'Salon',
  'services_label': 'Services',
  'no_service_selected': 'Aucun service sélectionné',
  'total_label': 'Total:',

  // Search Page
  'search_hint': 'Lawej aala salon, service...',
  'no_results_found': 'Ma l9inech ntija...',
  'salon_name_default': 'Nom du salon',
  'address_unavailable': 'Adresse non disponible',
  'search_empty_state': 'Lawj 3la 7ajjem wala service...',

  // Client Home & Appointments
  'professional_label': 'Professionnel: {0}',
  'category_haircut': 'Hjema',
  'category_facial': 'Soin Visage',
  'category_kids': 'Sghar',
  'review_modal_title': 'Sa77a L\'7jema!',
  'review_modal_desc': 'Rendez-vous mte3ek maa {0} fi salon \'{1}\' kmal.',
  'review_modal_question': '3jebtek l7jema?',
  'review_comment_hint': 'Khali commentaire (optionnel)...',
  'submit_review_btn': 'Abaath l\'avis',
  'skip_btn': 'Fout',
  'close_btn': 'Fermer',
};
